resources:
  - deployment.yaml
  - dsPrivateKeyVaultSecret.yaml
  - gateway.yaml
  - httpRoute.yaml
  - jwtAuthorizationPolicy.yaml
  - namespace.yaml
  - requestAuthentication.yaml
  - svc.yaml
  - trust1-serviceaccount.yaml
  - vaultAuth.yaml
  - waypoint.yaml

  
